# Override only for local development; do not sync to prod servers.

services:
  mariadb:
    # ports:
    #   - "${MARIADB_PORT_FORWARD:-127.0.0.1:3306}:3306"
    network_mode: ""
    networks:
      - "mynetwork"

  mariapersist:
    # ports:
    #   - "${MARIAPERSIST_PORT_FORWARD:-127.0.0.1:3333}:3333"
    network_mode: ""
    networks:
      - "mynetwork"

  mariapersistreplica:
    network_mode: ""
    networks:
      - "mynetwork"

  mariabackup:
    network_mode: ""
    networks:
      - "mynetwork"

  web:
    ports:
      - "${DOCKER_WEB_PORT_FORWARD:-127.0.0.1:8000}:${PORT:-8000}"
    network_mode: ""
    networks:
      - "mynetwork"
    volumes:
      - "./aacid_small/annas_archive_meta__aacid__duxiu_records__20240130T000000Z--20240305T000000Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__duxiu_records__20240130T000000Z--20240305T000000Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__duxiu_files__20240312T053315Z--20240312T133715Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__duxiu_files__20240312T053315Z--20240312T133715Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__ia2_acsmpdf_files__20231008T203648Z--20240126T083250Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__ia2_acsmpdf_files__20231008T203648Z--20240126T083250Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__ia2_records__20240126T065114Z--20240126T070601Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__ia2_records__20240126T065114Z--20240126T070601Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__worldcat__20231001T025039Z--20231001T235839Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__worldcat__20231001T025039Z--20231001T235839Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__zlib3_files__20230808T051503Z--20240402T183036Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__zlib3_files__20230808T051503Z--20240402T183036Z.jsonl.seekable.zst"
      - "./aacid_small/annas_archive_meta__aacid__zlib3_records__20230808T014342Z--20240322T220922Z.jsonl.small.seekable.zst:/file-data/annas_archive_meta__aacid__zlib3_records__20230808T014342Z--20240322T220922Z.jsonl.seekable.zst"
      - "../annas-archive-dev--temp-dir:/temp-dir"

  elasticsearch:
    # ports:
    #   - "${ELASTICSEARCH_PORT_FORWARD:-127.0.0.1:9200}:9200"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    network_mode: ""
    networks:
      - "mynetwork"

  elasticsearchaux:
    # ports:
    #   - "${ELASTICSEARCHAUX_PORT_FORWARD:-127.0.0.1:9201}:9201"
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "cluster.routing.allocation.disk.threshold_enabled=false"
    network_mode: ""
    networks:
      - "mynetwork"

  kibana:
    ports:
      - "${KIBANA_PORT_FORWARD:-127.0.0.1:5601}:5601"
    network_mode: ""
    networks:
      - "mynetwork"

  mailpit:
    ports:
      - '127.0.0.1:8025:8025' # web ui
    network_mode: ""
    networks:
      - "mynetwork"

networks:
  mynetwork:
